spring.application.name=s18d2

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fruitveg_s19d1
spring.datasource.username=postgres
spring.datasource.password=hello
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true